 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fenetre;


import javax.swing.JOptionPane;
import java.sql.*;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author Mr Richy
 */
public class FormAcceuil extends javax.swing.JFrame {

    /**
     * Creates new form FormAcceuil
     */
    public FormAcceuil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tMatricule = new javax.swing.JTextField();
        tNom = new javax.swing.JTextField();
        tPrenom = new javax.swing.JTextField();
        tSexe = new javax.swing.JTextField();
        tAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jbSave = new javax.swing.JButton();
        jbSupp = new javax.swing.JButton();
        jbUpdate = new javax.swing.JButton();
        jbAnnuler = new javax.swing.JButton();
        jbAfficher = new javax.swing.JButton();
        tRecherche = new javax.swing.JTextField();
        JbRecherche = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(50, 100));
        setName("Gestion Etudiants"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Gestion des etudiants");

        jLabel2.setText("Matricule");

        jLabel3.setText("Nom");

        jLabel4.setText("prenom");

        jLabel5.setText("Age");

        jLabel6.setText("Sexe");

        tMatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMatriculeActionPerformed(evt);
            }
        });

        tNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomActionPerformed(evt);
            }
        });

        table.setForeground(new java.awt.Color(51, 51, 51));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom", "Matricule", "Prenom", "Age", "Sexe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jbSave.setBackground(new java.awt.Color(255, 153, 255));
        jbSave.setText("Enregistrer");
        jbSave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbSaveFocusGained(evt);
            }
        });
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jbSupp.setBackground(new java.awt.Color(102, 255, 255));
        jbSupp.setText("Supprimer");
        jbSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuppActionPerformed(evt);
            }
        });

        jbUpdate.setBackground(new java.awt.Color(102, 255, 255));
        jbUpdate.setText("Modifier");
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });

        jbAnnuler.setBackground(new java.awt.Color(255, 153, 255));
        jbAnnuler.setText("Annuler");
        jbAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnnulerActionPerformed(evt);
            }
        });

        jbAfficher.setBackground(new java.awt.Color(102, 255, 255));
        jbAfficher.setText("Afficher");
        jbAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAfficherActionPerformed(evt);
            }
        });

        tRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRechercheActionPerformed(evt);
            }
        });

        JbRecherche.setBackground(new java.awt.Color(102, 255, 255));
        JbRecherche.setText("Rechercher");
        JbRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbRechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tSexe)
                            .addComponent(tAge)
                            .addComponent(tNom, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tMatricule)
                            .addComponent(tPrenom)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAnnuler)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbAfficher)
                .addGap(80, 80, 80)
                .addComponent(jbSupp)
                .addGap(111, 111, 111)
                .addComponent(jbUpdate)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(tRecherche)
                .addGap(57, 57, 57)
                .addComponent(JbRecherche)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JbRecherche)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSave)
                            .addComponent(jbAnnuler)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSupp)
                    .addComponent(jbAfficher)
                    .addComponent(jbUpdate))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnnulerActionPerformed
        // TODO add your handling code here:
        tNom.setText("");
        tMatricule.setText("");
        tPrenom.setText("");
        tAge.setText("");
        tSexe.setText("");
    }//GEN-LAST:event_jbAnnulerActionPerformed

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbetudiant", "root", "");

            String Nom = tNom.getText();
            String Matricule = tMatricule.getText();
            String Prenom = tPrenom.getText();
            String Age = tAge.getText();

            int IAge = Integer.parseInt(Age);

            String Sexe = tSexe.getText();
            PreparedStatement st = con.prepareStatement("INSERT INTO etudiant  VALUES(?,?,?,?,?)");
            st.setString(1, Nom);
            st.setString(2, Matricule);
            st.setString(3, Prenom);
            st.setInt(4, IAge);
            st.setString(5, Sexe);
            st.executeUpdate();
            
           
     
      JOptionPane.showMessageDialog(null, "Connexion reusssite avec succes");
      
        } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Ajout non effectuees"+e.getMessage());
     e.printStackTrace();
        }

    }//GEN-LAST:event_jbSaveActionPerformed

    private void jbSaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbSaveFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSaveFocusGained

    private void jbAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAfficherActionPerformed
        // TODO add your handling code here:
        try{
                
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbetudiant", "root", "");
   
                        Statement st = con.createStatement();
                        String query= "select *from etudiant";
                        ResultSet rs= st.executeQuery(query);
                        
                                table.setModel(DbUtils.resultSetToTableModel(rs));
                                
        }
        catch( Exception e){
            
                 JOptionPane.showConfirmDialog(null, "erreur d'affichage des donnees");
        }
    }//GEN-LAST:event_jbAfficherActionPerformed

    private void jbSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuppActionPerformed
        // TODO add your handling code here:
        
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                
                Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/dbetudiant", "root", "");
                String Matricule= tMatricule.getText();
//                int Imatricule=String.(Matricule);
                PreparedStatement st = con.prepareStatement("DELETE FROM etudiant  WHERE Matricule=?");
                st.setString(1, Matricule);
                st.executeUpdate();
                  JOptionPane.showMessageDialog(null, "Suppression effectuer avec succes");
        }
             catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Suppression non effectuer avec succes");
                        
                        }
    }//GEN-LAST:event_jbSuppActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbetudiant", "root", "");
            String Nom = tNom.getText();
            String Matricule = tMatricule.getText();
            String Prenom = tPrenom.getText();
            String Age = tAge.getText();
            int IAge = Integer.parseInt(Age);
            String Sexe = tSexe.getText();
            PreparedStatement st = con.prepareStatement("UPDATE etudiant set  Nom=?,Prenom=?,Age=?,Sexe=? WHERE Matricule=? ");

            st.setString(1, Nom);
            st.setString(2, Prenom);
            st.setInt(3, IAge);
            st.setString(4, Sexe);
            st.setString(5, Matricule);
            st.executeUpdate();

            JOptionPane.showMessageDialog(null, "modification reussite avec succees");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "echec de la modification");
          
        }
        
        
    
        
    }//GEN-LAST:event_jbUpdateActionPerformed

    private void tRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRechercheActionPerformed

    private void JbRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbRechercheActionPerformed
            // TODO add your handling code here:

         String query= "select *from etudiant where Nom=?";
        try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/dbetudiant", "root", "");
                String Recherche= tRecherche.getText();
                   PreparedStatement st = con.prepareStatement(query);
                       st.setString(1, Recherche);
                        ResultSet rs= st.executeQuery();
                        
                                table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
               JOptionPane.showMessageDialog(null, "cette etudiant n'existe pas desole");
        }
        
    }//GEN-LAST:event_JbRechercheActionPerformed

    private void tMatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMatriculeActionPerformed

    private void tNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAcceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbRecherche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAfficher;
    private javax.swing.JButton jbAnnuler;
    private javax.swing.JButton jbSave;
    private javax.swing.JButton jbSupp;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JTextField tAge;
    private javax.swing.JTextField tMatricule;
    private javax.swing.JTextField tNom;
    private javax.swing.JTextField tPrenom;
    private javax.swing.JTextField tRecherche;
    private javax.swing.JTextField tSexe;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
